titan:
  build: titan
  links:
    - elasticsearch
    - cassandra
  ports:
    - "8182:8182"
    - "8183:8183"
    - "8184:8184"
  restart: always

elasticsearch:
  image: elasticsearch
  restart: always

cassandra:
  image: spotify/cassandra
  restart: always
